version: "0.0"

services:
  postgres_db:
    image: postgis/postgis:latest
    hostname: postgres-db
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./db_data/:/docker-entrypoint-initdb.d/
