# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
 
  postgres:
    image: postgres:latest
    hostname: postgres-db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "max_connections=200"]
    ports:
      - 5432:5432
    expose:
      - "5432"
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy